apiVersion: v1
kind: Service
metadata:
  labels:
    app: reviveadserver
  name: reviveadserver
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: reviveadserver
